name: Unit Test

on:
  push:
    branches: [ "main" ]
  schedule:
      - cron:  '0 3 * * *'

jobs:
  unit-test:
    name: Run unit tests with wp-env
    runs-on: ubuntu-latest
    steps:
      - name: checkout repos
        uses: actions/checkout@v4
      - name: Config Composer Token
        run: composer config github-oauth.github.com secrets.GITHUB_TOKEN
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: yes
          args: --profile --ignore-platform-reqs
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm update
      - name: launch wp-env
        run: npm run env:start
      - name: wp-env debug infomation
        run: |
          php --version
          npm --version
      - name: Unit Test
        run: npm run test:run
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: wakatchi/um-utils