name: Unit Test

on:
  push:
    branches: [ "main" ]
  schedule:
      - cron:  '0 3 * * *'

jobs:
  unit-test:
    name: Run nit tests with wp-env
    runs-on: ubuntu-latest
    steps:
      - name: checkout repos
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: yes
          args: --profile --ignore-platform-reqs
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: launch wp-env
        run: npm run env:start
      - name: wp-env debug infomation
        run: |
          php --version
          npm --version
      - name: Unit Test
        run: npm run test:run --coverage-clover clover.xml
      - name: Generate test coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        with:
          coverage_badge_path: 'badge-coverage.svg'
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
